language: java
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
before_install: 
  - chmod +x ./script/cibuild
  - echo https://$API_username:$API_password@* > WSDL_access.txt

script: ./script/cibuild.sh

branches:
  only:
  - build

sudo: false

notifications:
  email: false