language: java
git:
  depth: false
jdk:
  - openjdk11
cache:
  directories:
    - "$HOME/.m2"
before_install: 
  - chmod +x ./script/cibuild
  - echo $WSDL_access > WSDL_access.txt

script: ./script/cibuild

branches:
  only:
  - build

sudo: false

notifications:
  email: false